name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: "glitch-tools/sync-glitch-github-action@master"
      env:
        GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
        GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
    - name: Run a one-line script
      run: echo Hello, world!
