name: Sync to Glitch (https://example-glitch-workflow.glitch.me/) # You can fill your master Glitch project's URL in here!
# See https://example-glitch-workflow.glitch.me/ for details on how this was set up.
on:
  push:
    branches:    
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: "glitch-tools/sync-glitch-github-action@master"
      env:
        GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
        GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
